version: "3.9"

services:
  postgres:
    image: postgis/postgis:14-3.3
    container_name: postgres14_postgis
    restart: always
    environment:
      POSTGRES_DB: vrisa_db
      POSTGRES_USER: fico
      POSTGRES_PASSWORD: admin123
    ports:
      - "5436:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d ambiente_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
